apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tests
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tests
  project: default
  sources:
  - repoURL: https://github.com/Calcagiara/argotests.git
    targetRevision: main
    path: nginx
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: baseline
        pod-security.kubernetes.io/enforce-version: latest
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
